[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/n8n/*"
  to = "https://esmagaygusuz4.app.n8n.cloud/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/zapier/*"
  to = "https://hooks.zapier.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
